name: Build & Deploy Jekyll site

permissions:
  contents: write
  pages: write
  id-token: write

on:
  push:
    branches:
      - source    # 소스 커밋 브랜치

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install system packages
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick

      - name: Prepare docs directory
        run: mkdir -p docs

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Jupyter
        run: pip install notebook

      - name: Install dependencies
        run: bundle install

      - name: Build site
        run: bundle exec jekyll build --destination docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: main
          publish_dir: docs
          force_orphan: true
